### ISSUE TITLE
After clean up mesh created is not hollow its solid

### ISSUE THREAD

**Issue by sntarkas** [Ugani-Prosthetics/ufit-blender#49]
In the 4th step of rotation the mesh created in the tutorial video is hollow (picture 1) but when we try to recreate it ,its not hollow its solid.(our trial).So in the following steps errors occur.
![picture 1](https://github.com/Ugani-Prosthetics/ufit-blender/assets/91329994/cd616d42-2579-4f93-b8f2-765ebdaef734)
![our trial](https://github.com/Ugani-Prosthetics/ufit-blender/assets/91329994/6a410180-219e-4ac4-b431-d201a027b04c)

**Comment by bertjanssens93** [comment]
This is the way the add-on is designed. By making it a closed mesh, we avoid problems in later steps.
